### ISSUE TITLE
GUY IS a joke

### ISSUE THREAD

**Issue by dschaf** [homeless1337/fortnite-base-ready-to-inject#3]
guy bans me from his discord after me saying that the base doesnt work and i have updated the offsets and sigs
why ban me for saying this

**Comment by homeless1337** [comment]
LOL MAN I DIDNT BAN YOU WHATS YOUR NAME

**Comment by homeless1337** [comment]
AAH THE GUY WITH NO SPREAD LMAO I BANNED YOU CUZ I HAD YOU BLOCKED

**Comment by dschaf** [comment]
can u unban me?
i was causing no harm and was helping some people and there before i got to add them
