### ISSUE TITLE
it really does crash doe

### ISSUE THREAD

**Issue by rubbyl33t** [homeless1337/fortnite-base-ready-to-inject#5]
the dllmain and Main functions run fine, however after the Main function it crashes fn
tested on 1903

**Comment by homeless1337** [comment]
yea im fixing it once im free

**Comment by pastebtw** [comment]
HI RETARDS HAHAHAHAHAHA
https://cdn.discordapp.com/attachments/763889008665034762/803789012442808350/Discord_1zqO3sJKqb.png
https://cdn.discordapp.com/attachments/763889008665034762/803789012442808350/Discord_1zqO3sJKqb.png
https://cdn.discordapp.com/attachments/763889008665034762/803789012442808350/Discord_1zqO3sJKqb.png
https://cdn.discordapp.com/attachments/763889008665034762/803789012442808350/Discord_1zqO3sJKqb.png
